<div class="content-accessibility-statement">
  <h1><?php echo do_shortcode('[mh_site_settings type="company_name"]')?> Accessibility Statement</h1>
  <h2>General</h2>
  <p><?php echo do_shortcode('[mh_site_settings type="company_name"]')?> strives to ensure that its services are accessible to people with disabilities. <?php echo do_shortcode('[mh_site_settings type="company_name"]')?> has invested a significant amount of resources to helpensure that its website is made easier to use and more accessible for people with disabilities, with the strong belief that every person has the right to live with dignity, equality, comfort and independence.</p>
  <h2>Accessibility on <?php echo do_shortcode('[mh_site_settings type="domain_name"]')?></h2>
  <p><a href="https://www.<?php echo do_shortcode('[mh_site_settings type="domain_name"]')?>">https://www.<?php echo do_shortcode('[mh_site_settings type="domain_name"]')?></a> makes available the UserWay Website Accessibility Widget that is powered by a dedicated accessibility server. The software allows <a href="https://www.<?php echo do_shortcode('[mh_site_settings type="domain_name"]')?>">https://www.<?php echo do_shortcode('[mh_site_settings type="domain_name"]')?></a> to improve its compliance with the Web Content Accessibility Guidelines (WCAG 2.1).</p>
  <h2>Enabling the Accessibility Menu</h2>
  <p>The <a href="https://www.<?php echo do_shortcode('[mh_site_settings type="domain_name"]')?>">https://www.<?php echo do_shortcode('[mh_site_settings type="domain_name"]')?></a> accessibility menu can be enabled either by hitting the tab key when the page first loads or by clicking the accessibility menu icon that appears on the corner of the page. After triggering the accessibility menu, please wait a moment for the accessibility menu to load in its entirety.</p>
  <h2>Disclaimer</h2>
  <p><?php echo do_shortcode('[mh_site_settings type="company_name"]')?> continues its efforts to constantly improve the accessibility of its site and services in the belief that it is our collective moral obligation to allow seamless, accessible and unhindered use also for those of us with disabilities.</p>
  <p>Despite our efforts to make all pages and content on <a href="https://www.<?php echo do_shortcode('[mh_site_settings type="domain_name"]')?>">https://www.<?php echo do_shortcode('[mh_site_settings type="domain_name"]')?></a> fully accessible, some content may not have yet been fully adapted to the strictest accessibility standards. This may be a result of not having found or identified the most appropriate technological solution.</p>
  <h2>Here For You</h2>
  <p>If you are experiencing difficulty with any content on <a href="https://www.<?php echo do_shortcode('[mh_site_settings type="domain_name"]')?>">https://www.<?php echo do_shortcode('[mh_site_settings type="domain_name"]')?></a> or require assistance with any part of our site, please contact us during normal business hours as detailed below and we will be happy to assist.</p>
  <h2>Contact Us</h2>
  <p>If you wish to report an accessibility issue, have any questions or need assistance, please contact us: <a href="tel:+1<?php echo do_shortcode('[mh_site_settings type="company_phone_1_link"]') ?>"><?php echo do_shortcode('[mh_site_settings type="company_phone_1"]') ?></a>.</p>
</div>
